# Aerospike Server - Enterprise Edition
# CF Make Variables Include File
# Makefile.vars

ifeq ($(USE_EE),1)
  INCLUDES += -I$(EEREPO)/cf/include

  VPATH += $(EEREPO)/cf/src

  HEADERS += arenax_ee.h
  HEADERS += fips_ee.h
  HEADERS += vault_ee.h
  HEADERS += vmapx_ee.h
  HEADERS += xmem_ee.h

  SOURCES += arenax_ee.c
  SOURCES += fips_ee.c
  SOURCES += socket_ee.c
  SOURCES += tls_ee.c
  SOURCES += vault_ee.c
  SOURCES += vmapx_ee.c
  SOURCES += xmem_ee.c
  SOURCES += xmem_flash.c
  SOURCES += xmem_pmem.c
  SOURCES += xmem_shmem.c
endif
