# Aerospike Server - Enterprise Edition
# Main Make Variables Include File
# Makefile.vars

# Build the Enterprise Edition?  [By default, no.]
USE_EE = 0
# Build the FIPS version?  [By default, no.]
USE_EE_FIPS = 0

# Paths to the submodules:
AS_EE := $(realpath $(EEREPO)/as)
LZ4 := $(realpath $(EEREPO)/modules/lz4)
SNAPPY := $(realpath $(EEREPO)/modules/snappy)
ZSTD := $(realpath $(EEREPO)/modules/zstd)
PMDK := $(realpath $(EEREPO)/modules/pmdk)

# Static libraries:
LZ4_LIB = $(LZ4)/lib/liblz4.a
SNAPPY_LIB = $(SNAPPY)/build/libsnappy.a
ZSTD_LIB = $(ZSTD)/lib/libzstd.a
PMEM_LIB = $(PMDK)/src/nondebug/libpmem.a

ifeq ($(USE_EE),1)
ifeq ($(USE_EE_FIPS),1)
  AS_EE_CFLAGS += -DAS_FIPS_MODE=true
else
  AS_EE_CFLAGS += -DAS_FIPS_MODE=false
endif
  AS_EE_CFLAGS += -DAS_CLUSTER_SZ=256
  AS_EE_CFLAGS += -DASC=AS_CLUSTER_SZ
  AS_EE_CFLAGS += -DCF_ARENAX_MAX_STAGES=2048
  AS_EE_CFLAGS += -DCF_ARENAX_MAX_STAGE_SIZE="(16L * 1024L * 1024L * 1024L)"
  AS_EE_CFLAGS += -DAS_NAMESPACE_SZ=32
  AS_EE_CFLAGS += -DAS_NODE_STORAGE_SZ=0L

  AS_LIBRARIES += $(LZ4_LIB)
  AS_LIBRARIES += $(PMEM_LIB)
  AS_LIBRARIES += $(SNAPPY_LIB)
  AS_LIBRARIES += $(ZSTD_LIB)

ifeq ($(USE_EE_FIPS),1)
  LIBRARIES += -Wl,-rpath=/opt/aerospike/lib/fips
  LIBRARIES += -L$(FIPSREPO)/devel/lib
endif
  LIBRARIES += -llber
  LIBRARIES += -lldap
  LIBRARIES += -lssl

ifeq ($(USE_EE_FIPS),1)
  INCLUDES += -I$(FIPSREPO)/devel/include
endif
  INCLUDES += -I$(LZ4)/lib
  INCLUDES += -I$(PMDK)/src/include
  INCLUDES += -I$(SNAPPY) -I$(SNAPPY)/build
  INCLUDES += -I$(ZSTD)/lib

ifeq ($(USE_EE_FIPS),1)
  EXT_CFLAGS += -I$(FIPSREPO)/devel/include
endif
endif

# Handle per-distro. build system differences:

# Name of "cmake" command to use:
ifeq ($(OS),$(filter $(OS),el6 el7 el8 amzn1 amzn2))
  CMAKE = cmake3
else
  CMAKE = cmake
endif

ifeq ($(OS),el6)
  # Access newer versions of development tools on CentOS 6.
  TOOLSET = scl enable devtoolset-2
  PMEM_FLAGS = NDCTL_ENABLE=n EXTRA_CFLAGS=-Dsecure_getenv=getenv
else
  ifeq ($(OS),debian7)
    TOOLSET = sh -c
    PMEM_FLAGS = NDCTL_ENABLE=n EXTRA_CFLAGS=-Dsecure_getenv=getenv check_Wconversion=0
  else
    TOOLSET = sh -c
    PMEM_FLAGS = NDCTL_ENABLE=n
  endif
endif
