# Aerospike Server - Enterprise Edition
# AS Make Variables Include File
# Makefile.vars

ifeq ($(USE_EE),1)
  INCLUDES += -I$(EEREPO)/cf/include
  INCLUDES += -I$(EEREPO)/as/include

  VPATH += $(EEREPO)/as/src

  BASE_HEADERS += features_ee.h
  BASE_HEADERS += index_ee.h
  BASE_HEADERS += ldap_ee.h
  BASE_HEADERS += rate_quota.h
  BASE_HEADERS += record_ee.h
  BASE_HEADERS += security_book.h
  BASE_HEADERS += security_ee.h
  BASE_HEADERS += security_role.h
  BASE_HEADERS += security_user.h
  BASE_HEADERS += session_token.h
  BASE_HEADERS += set_index_ee.h

  BASE_SOURCES += bin_ee.c
  BASE_SOURCES += cfg_ee.c
  BASE_SOURCES += index_ee.c
  BASE_SOURCES += ldap_ee.c
  BASE_SOURCES += namespace_ee.c
  BASE_SOURCES += proto_ee.c
  BASE_SOURCES += rate_quota.c
  BASE_SOURCES += record_ee.c
  BASE_SOURCES += security.c
  BASE_SOURCES += security_book.c
  BASE_SOURCES += security_info.c
  BASE_SOURCES += security_role.c
  BASE_SOURCES += security_user.c
  BASE_SOURCES += session_token.c
  BASE_SOURCES += set_index_ee.c
  BASE_SOURCES += truncate_ee.c

  ifeq ($(STATIC_LIB),1)
    BASE_SOURCES += features_lib_ee.c
  else
    BASE_SOURCES += features_ee.c
  endif

  FABRIC_HEADERS += appeal_ee.h
  FABRIC_HEADERS += meta_batch_ee.h
  FABRIC_HEADERS += migrate_ee.h
  FABRIC_HEADERS += partition_balance_ee.h
  FABRIC_HEADERS += partition_ee.h

  FABRIC_SOURCES += appeal_ee.c
  FABRIC_SOURCES += meta_batch_ee.c
  FABRIC_SOURCES += migrate_ee.c
  FABRIC_SOURCES += partition_balance_ee.c
  FABRIC_SOURCES += partition_ee.c
  FABRIC_SOURCES += roster_ee.c

  SINDEX_SOURCES += gc_ee.c
  SINDEX_SOURCES += sindex_tree_ee.c

  STORAGE_HEADERS += drv_common_ee.h
  STORAGE_HEADERS += flat_ee.h

  STORAGE_SOURCES += drv_common_ee.c
  STORAGE_SOURCES += drv_memory_ee.c
  STORAGE_SOURCES += drv_pmem_ee.c
  STORAGE_SOURCES += drv_ssd_ee.c
  STORAGE_SOURCES += flat_ee.c

  TRANSACTION_HEADERS += re_replicate_ee.h

  TRANSACTION_SOURCES += delete_ee.c
  TRANSACTION_SOURCES += re_replicate_ee.c
  TRANSACTION_SOURCES += replica_ping_ee.c
  TRANSACTION_SOURCES += rw_utils_ee.c

  XDR_HEADERS += cluster.h
  XDR_HEADERS += dc.h
  XDR_HEADERS += dc_manager.h
  XDR_HEADERS += reader.h
  XDR_HEADERS += ship.h

  XDR_SOURCES += cluster.c
  XDR_SOURCES += dc.c
  XDR_SOURCES += dc_manager.c
  XDR_SOURCES += info.c  
  XDR_SOURCES += reader.c
  XDR_SOURCES += ship.c
  XDR_SOURCES += xdr_ee.c
endif
